server:
  port: 8080
  error:
    include-message: always

spring:
  jackson:
    time-zone: Asia/Seoul
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${client_id}
            client-secret: ${client_secret}
            scope: identify
            redirect-uri: "{baseUrl}/account/oauth/discord"
            authorization-grant-type: authorization_code
            client-name: Discord
            provider: discord
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me

springdoc:
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: false
  use-fqn: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion : none