server:
  port: 8080
  error:
    include-message: always

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${client_id}
            client-secret: ${client_secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
            client-name: Discord
            provider: discord
            scope:
              - identify
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id

springdoc:
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: false
  use-fqn: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion : none